{-|
Module      : Parse.Parser
Description : Parses a stream of tokens into an Abstract Syntax Tree (AST).
Author      : Michał Kośka

This module is responsible for taking raw tokens generated by the Tokeniser
and structuring them into executable operations, including commands and redirections.
-}

module Parse.Parser where

import qualified Data.Text as T

import Exec.Command
import Types

walkAST :: [T.Text] -> Either T.Text AST
walkAST token_list = 
  let is_bg = not (null token_list) && last token_list == "&"
      tokens_to_parse = if is_bg then init token_list else token_list      

      (left_side, right_side) = break (\x -> x `elem` [">", "1>", "2>", ">>", "1>>", "2>>"]) tokens_to_parse
   
      ast_node = case right_side of
        [] -> parseCommand left_side

        (operator : file : rest) ->
          let redirection_type = case operator of
                t | t `elem` ["2>", "2>>"] -> ErrorRedirection
                _    -> StandardRedirection
              write_method = case operator of
                t | t `elem` [">>", "1>>", "2>>"] -> AppendMethod
                _ -> TruncateMethod

          in case walkAST (left_side ++ rest) of 
            Left _err     -> Left _err
            Right cmd_ast -> Right (RedirectNode redirection_type cmd_ast (T.unpack file) write_method)
        
        [_] -> Left "error"
  in if is_bg
    then fmap BackgroundJobNode ast_node
    else ast_node

parseCommand :: [T.Text] -> Either T.Text AST
parseCommand input_command = 
  let  
  in case input_command of
    ["cd"]          -> Right $ ExecNode (BuiltIn (Cd "~"))
    ("cd":(x:args)) -> Right $ ExecNode (BuiltIn (Cd x))
    ("exit":_)      -> Right $ ExecNode (BuiltIn Exit)
    ("echo":args)   -> Right $ ExecNode (BuiltIn (Echo args))
    ("type":args)   -> Right $ ExecNode (BuiltIn (Type args))
    ("pwd":_)       -> Right $ ExecNode (BuiltIn Pwd)
    ("complete":a)  -> Right $ ExecNode (BuiltIn (Complete a))
    ("jobs":a)      -> Right $ ExecNode (BuiltIn (Jobs))
    (unknown:args)  -> Right $ ExecNode (External unknown args)
    _               -> Right $ ExecNode Blank

parseFlags :: [T.Text] -> ([T.Text], [T.Text])
parseFlags input =
  let (flags, args) = go [] input
  in (reverse flags, args)
  where
    go :: [T.Text] -> [T.Text] -> ([T.Text], [T.Text])
    go acc [] = (acc, [])

    go acc ("--":rest) = (acc, rest)

    go acc (x:xs)
      | "--" `T.isPrefixOf` x =
          go (T.drop 2 x : acc) xs

      | "-" `T.isPrefixOf` x =
          let shorts = map T.singleton (T.unpack (T.drop 1 x))
          in go (reverse shorts ++ acc) xs

      | otherwise =
          (acc, x:xs)